### PR TITLE
Gamepad fixes, SDL2 Config & Initial debug menu support

### PR DESCRIPTION
**Pull request by ZLau92**
Sorry for the duplicate pull request, just getting used to version controlling.
#685 
The highlight here is I've gotten some initial gamepad compatibility for the debug menu. More details about that in the commit.

Also a pull request from earlier with SDL gamepad configs from environment variables.

Plus a couple cam/anim bugfixes I've come across.
#843

### CODE REVIEW

**Comment by erorcun** [comment]
You should mark/wrap changes that's done to original code, this is a reverse engineering oriented project.
so I'm not in favor of adding `\n` to Renderer.cpp. also you should explain your change in Automobile.cpp. other changes look ok to me, but I think @aap should decide it since he is the author of debugmenu.

**Comment by ZLau92** [comment]
Ok, duly noted.

**Comment by ZLau92** [comment]
@erorcun thanks, and apologies for any confusion as I become familiar with the process of contributing in general.
For Automobile.cpp, the change I made was to address an issue whereby the driveby_r animation wouldn't play unless you have 0 passengers or are in first person mode. I removed the if() portion of the else if clause that was causing this to happen.
I wasn't able to replicate this behavior in the ps2 versions of iii/vc.

**Comment by ZLau92** [comment]
Looks like this PR may have gotten a bit messy. I'm going to close it and break these changes out.

**Pull request closed without merging**
