### PR TITLE
Fixing an original issue: removing unneeded white color codes

### PR DESCRIPTION
**Pull request by IlDucci**
This is an original issue. It seems that certain cutscenes had a white color control code in their subtitles when
 - It's not needed for subtitles.
 - The `~w~` control code isn't pure white, but light gray, so those subtitles look different than the rest.

I've also fixed a couple of unwanted spaces found in French and German, and also tweaked one string in Spanish and added the translation for the new Waypoint string.

### CODE REVIEW

**Comment by IlDucci** [comment]
Changes unwelcomed by the core team.

**Comment by Calinou** [comment]
> Changes unwelcomed by the core team.

Out of curiosity, why is that?

**Comment by IlDucci** [comment]
The team considered those ~w~ codes to be placed on purpose and not leftovers that should be removed. I'm going to do another PR to fix actual typos.

**Comment by Calinou** [comment]
Superseded by https://github.com/GTAmodding/re3/pull/923.

**Pull request closed without merging**
